steps:
# Install dependencies
- name: node
  entrypoint: npm
  args: ['ci']
# Run tests
- name: node
  entrypoint: npm
  args: ['test']
# Run custom commands
- name: node
  entrypoint: npm
  args: ['run', 'build']